### ISSUE TITLE
Regarding Code/Data Release

### ISSUE THREAD

**Issue by brihijoshi** [CannyLab/anthology#1]
Hi Team! 

Thanks for the great work, I am excited to play around with the code/dataset. Do you have an estimate of when you'd be releasing it? Would be super grateful about that!

**Comment by SuhongMoon** [comment]
Hi!

Thank you for your interest in our project. We're excited to share that the code and dataset will be released soon. Stay tuned!

**Comment by cat0ne** [comment]
Hello, do you still plan to release the code and dataset? Thanks

**Comment by SuhongMoon** [comment]
Hi @brihijoshi and @cat0ne, apologies for the delayed update. We have uploaded the codebase to reproduce the results from the paper. However, the backstory dataset is still awaiting approval, and we will share it as soon as it is available. In the meantime, you can generate the backstories yourself using the script `scripts/run_backstory_gen.py`
